# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Test Alpha Build

on:
  push:
    branches: [ "master", "guitest" ]
  pull_request:
    branches: [ "master", "guitest" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Give execute permission to gradlew
      run: chmod u+x ./gradlew # Gib dem Skript die Ausführungsberechtigung
    - name: Build Plugin
      run: ./gradlew build # Ersetze dies mit dem Befehl, um dein Plugin zu bauen
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
          # Artifact name
          name: FalexHomes-0.1.0-Alpha.jar
          # Destination path
          path: ${{ github.workspace }}/build/libs/FalexHomes-0.1.0-Alpha.jar
